utf-8utf-8importos
importcv2
fromPILimportImage
frompyrogramimportClient,filters
fromShrutiMusicimportapp


@app.on_message(filters.command("tiny"))
asyncdeftiny_sticker(client,message):
    reply=message.reply_to_message
ifnot(replyandreply.sticker):
        awaitmessage.reply("Please reply to a sticker")
return
kontol=awaitmessage.reply("Processing please wait")
awaitkontol.edit_text("🐾")
ik=awaitapp.download_media(reply)
im1=Image.open("ShrutiMusic/assets/shruti.png")
ifik.endswith(".tgs"):
        awaitapp.download_media(reply,"wel2.tgs")
os.system("lottie_convert.py wel2.tgs json.json")
withopen("json.json","r")asjson_file:
            jsn=json_file.read()
jsn=jsn.replace("512","2000")
withopen("json.json","w")asjson_file:
            json_file.write(jsn)
os.system("lottie_convert.py json.json wel2.tgs")
file="wel2.tgs"
os.remove("json.json")
elifik.endswith((".gif",".mp4")):
        iik=cv2.VideoCapture(ik)
_,busy=iik.read()
cv2.imwrite("i.png",busy)
fil="i.png"
im=Image.open(fil)
z,d=im.size
ifz==d:
            xxx,yyy=200,200
else:
            t=z+d
a=z/t
b=d/t
aa=(a*100)-50
bb=(b*100)-50
xxx=200+5*aa
yyy=200+5*bb
k=im.resize((int(xxx),int(yyy)))
k.save("k.png",format="PNG",optimize=True)
im2=Image.open("k.png")
back_im=im1.copy()
back_im.paste(im2,(150,0))
back_im.save("o.webp","WEBP",quality=95)
file="o.webp"
os.remove(fil)
os.remove("k.png")
else:
        im=Image.open(ik)
z,d=im.size
ifz==d:
            xxx,yyy=200,200
else:
            t=z+d
a=z/t
b=d/t
aa=(a*100)-50
bb=(b*100)-50
xxx=200+5*aa
yyy=200+5*bb
k=im.resize((int(xxx),int(yyy)))
k.save("k.png",format="PNG",optimize=True)
im2=Image.open("k.png")
back_im=im1.copy()
back_im.paste(im2,(150,0))
back_im.save("o.webp","WEBP",quality=95)
file="o.webp"
os.remove("k.png")
awaitapp.send_document(message.chat.id,file,reply_to_message_id=message.id)
awaitkontol.delete()
os.remove(file)
os.remove(ik)
